version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: asupara7/circledock
    environment:
      - PROJECT_NAME: elegant-beach-194805
      - CONTAINER_NAME: quickstart
      - CLUSTER_NAME:  testproject
      - CLOUDSDK_COMPUTE_ZONE: asia-east1-a
      - GOOGLE_APPLICATION_CREDENTIALS: ${HOME}/account-auth.json

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Check docker version
          command: |
            unset ${!DOCKER*}
            rc-update add docker boot
            whoami
            docker version
      - run:
          name: Build application Docker image
          command: |
            docker build -t gcr.io/${PROJECT_NAME}/${CONTAINER_NAME}:$CIRCLE_SHA1 .
            docker tag gcr.io/${PROJECT_NAME}/${CONTAINER_NAME}:$CIRCLE_SHA1 gcr.io/${PROJECT_NAME}/${CONTAINER_NAME}:latest
      - run:
          name: Run tests
          command: |
            bundle exec rake
      - deploy:
          name: Deploy application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo $ACCT_AUTH | base64 -d > ${HOME}/account-auth.json
              gcloud auth activate-service-account --key-file ${HOME}/account-auth.json
              gcloud config set project $PROJECT_NAME
              gcloud --quiet config set container/cluster $CLUSTER_NAME
              gcloud config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
              gcloud --quiet container clusters get-credentials $CLUSTER_NAME
              gcloud config set container/use_client_certificate True
              ./deploy.sh
            fi
