apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deployment-testProject
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: deployment-testProject
    spec:
      containers:
      - name: ${CONTAINER_NAME}
        image: gcr.io/${PROJECT_NAME}/${CONTAINER_NAME}:${CIRCLE_SHA1}
        ports:
        - containerPort: 80
