apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ${CONTAINER_NAME}
  labels:
    app: ${CONTAINER_NAME}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${CONTAINER_NAME}
  template:
    metadata:
      labels:
        app: ${CONTAINER_NAME}
    spec:
      containers:
      - name: ${CONTAINER_NAME}
        image: gcr.io/${PROJECT_NAME}/${CONTAINER_NAME}:${CIRCLE_SHA1}
        ports:
        - containerPort: 80
