apiVersion: v1
kind: Service
metadata:
  name: ${CONTAINER_NAME}
spec:
  selector:
    app: ${CONTAINER_NAME}
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
